Use SCHOOL
go

SELECT * FROM CourseMaster
GO

-- Highest Fee Course
SELECT COURSENAME 
FROM CourseMaster 
WHERE Fee = 
(SELECT MAX(FEE) FROM CourseMaster)
GO

--10TH HIGHEST FEE
SELECT COURSENAME 
FROM CourseMaster
WHERE Fee = 
		(
		SELECT MIN(FEE) FROM
			(
			SELECT TOP 10 FEE FROM CourseMaster
			ORDER BY Fee DESC
		) AS K
)

-- GROUP BY
SELECT CATEGORY, 
		SUM(FEE) AS TOTALFEEPERCATEGORY,
		AVG(FEE) AS AVGFEEPERCATEGORY,
		MIN(FEE) AS MINFEEPERCATEGORY,
		MAX(FEE) AS MAXFEEPERCATEGORY
FROM CourseMaster
GROUP BY Category
GO

-- RANKING - ROWNO
SELECT CATEGORY, 
		COURSENAME,
		FEE,
		DENSE_RANK() OVER (PARTITION BY CATEGORY ORDER BY FEE DESC) AS DENSE_RANKNO,
		RANK() OVER (PARTITION BY CATEGORY ORDER BY FEE DESC) AS RANKNO,
		ROW_NUMBER() OVER (PARTITION BY CATEGORY ORDER BY FEE DESC) AS ROWNO
FROM CourseMaster
GO

UPDATE CourseMaster
SET FEE = 9000
WHERE CID IN (103, 109,115)
GO

-- DATE FUNCTIONS
SELECT * FROM EnrollmentMaster
GO

SELECT *,CONVERT(varchar,DOE,101) AS NEWDATE FROM EnrollmentMaster
GO

--DATEDIFF
SELECT *, DATEDIFF(DD,DOE,GETDATE()) AS NOOFDAYSOLD FROM EnrollmentMaster
GO

-- DATEADD
SELECT *, DATEADD(YY,1,DOE) AS FUTUREDATE1 FROM EnrollmentMaster
GO

SELECT *, DATEADD(MM,12,DOE) AS FUTUREDATE2 FROM EnrollmentMaster
GO

SELECT *, DATEADD(DD,365,DOE) AS FUTUREDATE3 FROM EnrollmentMaster
GO

SELECT *, DATEADD(HH,24,DOE) AS FUTUREDATE4 FROM EnrollmentMaster
GO

